- image_manager.cpp
IBM sets the Extended Version to NNXXXX_YYY where NN is the platform
identifier (a subset of machine name). Add a check so that if Extended
Version matches this format, it checks that the platform is the same,
otherwise fail the same as with a machine name miscompare.
Tested:
- Verified a system running extended version NL failed to update
to an image with ML even though both have p10bmc as machine name:
.ExtendedVersion   property  s   "NL1030_007"
Aug 15 19:53:07 p10bmc phosphor-version-software-manager[1959]: BMC
upgrade: Platform name doesn't match: L vs M
Aug 15 19:53:07 p10bmc phosphor-version-software-manager[1959]: An error
occured processing the image.
Aug 15 19:53:07 p10bmc phosphor-version-software-manager[1959]: Error
(-1) processing image /tmp/images/01NM1030_007_007.tar
- …
> image_manager: Add check for IBM extended version format

- activation.cpp
Just log a trace, since creating errors from a local yaml file and from
phosphor-dbus-interfaces in the same file is not supported.
A new Busy failure would need to be added to phoshpor-dbus-interfaces to
support logging an error.
Change-Id: I0c8e14c8ad5c5a37fbb62e3c2d2f0e6ecc4cd8ee
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>
> activation: Remove the BusyFailure error log 

- download_manager.cpp
- image_manager.cpp
- image_verify.cpp
- item_updater.cpp
- serialize.cpp
- static/flash.cpp
- sync_manager.cpp
- sync_watch.cpp
- usb/usb_manager.cpp
- watch.cpp
The currently used filesystem method will cause an exception if the file system is damaged for some reason, resulting in a core dump of the process.
So the overloaded method with the error_code parameter should be used here to ensure that the process core dump will not be caused after an exception is thrown.
Fixes: openbmc/phosphor-bmc-code-mgmt#12
Tested: built phosphor-bmc-code-mgmt successfully and CI passes.
Signed-off-by: George Liu <liuxiwei@inspur.com>
Change-Id: I329f78b481cb466e755bc1b78562583620f561c2
> Fix the core dump by using filesystem error_code

- msl_verify.cpp
- msl_verify.hpp
```
Currently, a MSL reset will write the GA level to VPD to allow all
downgrades to be performed.
Change it so that the reset request creates a temporary file that would
signal the code update process to write the MSL to the version of the
subsequent update. Therefore when a reset MSL is issued, and a system is
downgraded to the first service pack for example, it would write that
level to VPD, preventing further downgrades to the GA level.
Tested: Verified the reset MSL allowed a downgrade and that the level
was written to VPD.
- First check the downgrade is blocked:
Apr 04 18:26:32 p10bmc phosphor-image-updater[547]: BMC Minimum Ship
Level (fw1040.00-20                    ) NOT met by
fw1020.30-24-1020.2314.20230329a (NL1020_099)
- Issue reset request:
root@p10bmc:~# …
```
> 1050: msl: reset: Set MSL to version of subsequent update (#51)

- activation.cpp
- activation.hpp
- gen-lids-image-tar
- lid.cpp
- lid.hpp
- uak_verify.cpp
- uak_verify.hpp
This commit defines the dbus interface “validate” that will be called during inband code updates. As of now, the interface checks the validity of the access key. If the access key has expired and field mode is enabled, the dbus returns an error specifying the problem.
This commit also adds restriction on HIPER service packs, being
allowed across GA levels. HIPER service packs only within the same
GA level will be allowed to be updated.
Example: If a customer is on a build with the GA level of fw1030, they
cannot move to the HIPER service pack released for fw1050.
Previously, HIPER service packs could be applied across GA levels
and this allowed customers to utilize the features of a latter service
pack without buying the service contract.
Tested:
Used busctl call “busctl call …
> Marker LID Validation : Define validation dbus interface Backend

- side-switch/phosphor-bmc-side-switch.service
```
Upstream yocto introduced a change via e510222 (systemd-systemctl:
fix instance template WantedBy symlink construction).
This fixes a bug that we in OpenBMC had been taking advantage of in that
we were able to document our templated target dependencies without it
actually doing anything. The real installation of services within
targets occurs in our bitbake recipes due to the complexity of chassis
and host instances on a per machine basis.
Leave the dependency information in the service files but comment them
out. It's useful to be able to look at a service and understand which
targets it's going to be installed into by the bitbake recipes.
In some cases, we had hard coded the target instance, which does install
the service correctly, but only in that one target. All services should …
```
> 1050: systemd: no installation in templated targets

- activation.cpp
- lid.cpp
- lid.hpp
- msl_verify.cpp
- msl_verify.hpp
Perform the minimum ship level check as part of the marker lid validation. This requires reading the SPNM ADF to get the firmware version string.
Move the UAK variables to the ifdef block that validates the UAK to avoid compile errors from platforms that don't have UAK check enabled.
Tested:
- Inband:
```
Aug 06 19:13:15 p10bmc phosphor-image-updater[537]: BMC Minimum Ship Level (fw1050.10-00                    ) NOT met by fw1050.00-99
Aug 06 19:13:15 p10bmc pldmd[1436]: Marker lid validate error, ERROR=sd_bus_call: xyz.openbmc_project.Software.Version.Error.Incompatible: A system component has a software version that is incompatible as determined by the implementation and needs to be updated. Some usage examples for this error include creating logging events and providing information on …
```
> Marker LID Validation: Add minimum ship level check

- activation.cpp
- activation.hpp
- lid.cpp
- lid.hpp
- uak_verify.cpp
- uak_verify.hpp
Change makes HIPER flag in marker lid independent of UAK enforcement
• UAK must be enforced on any X movement on FW10NN.XY
• UAK is not enforced on any Y movement on FW10NN.XY
• If the "one off" flag is set then UAK enforcement is ignored
> Increased UAK enforcement

- activation.cpp
- activation.hpp
- lid.cpp
- lid.hpp
- uak_verify.cpp
- uak_verify.hpp
- usb/usb_manager.cpp
```
Change makes HIPER flag in marker lid independent of UAK enforcement
• UAK must be enforced on any X movement on FW10NN.XY
• UAK is not enforced on any Y movement on FW10NN.XY
• If the "one off" flag is set then UAK enforcement is ignored
Signed-off-by: Sagar Srinivas <sagar.srinivas@ibm.com>```
> 1060: Increased UAK enforcement (#23)

- uak_verify.cpp
In the current code, UAK is not enforced on X movement on a 10NN.XY build as part of the changes that was merged for 1M4 line item:
https://github.com/ibm-openbmc/phosphor-bmc-code-mgmt/pull/23
This commit fixes it and adds enforcement on X movement and not on the Y movement.
> Increased UAK enforcement on X movement

- image_manager.cpp
- software_manager_tool.cpp
This is to allow P10 systems to be updated to P-Future images and vice versa.
Tested on simics. With this change, running `software-manager-tool --ignore_machine_name` allows the update to go ahead with an image with a different machine name field.
> Add bypass in code updates for machine name

- item_updater.hpp
- msl_verify.cpp
- msl_verify.hpp
The Minimum Version is now an available D-Bus interface:
```
https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/70110
```
Populate its value if it's being defined.
Tested: If the msl meson options are defined, the D-Bus property is populated with the value of the defined minimum version:
```
root@witherspoon:~# busctl get-property xyz.openbmc_project.Software.BMC.Updater /xyz/openbmc_project/software xyz.openbmc_project.Software.MinimumVersion MinimumVersion
s "2.15.0"
```
Change-Id: I0f9df0cfd7c06794df836e161b3416094a8535de
> 1050: Populate MinimumVersion property

- item_updater.hpp
- msl_verify.cpp
- msl_verify.hpp
The Minimum Version is now an available D-Bus interface:
```
https://gerrit.openbmc.org/c/openbmc/phosphor-dbus-interfaces/+/70110
```
Populate its value if it's being defined.
Tested: If the msl meson options are defined, the D-Bus property is populated with the value of the defined minimum version:
```
root@witherspoon:~# busctl get-property xyz.openbmc_project.Software.BMC.Updater /xyz/openbmc_project/software xyz.openbmc_project.Software.MinimumVersion MinimumVersion
s "2.15.0"
```
Change-Id: I0f9df0cfd7c06794df836e161b3416094a8535de
> 1060: Populate MinimumVersion property

- item_updater.cpp
- item_updater.hpp
Per feedback from the bmcweb maintainers, move the recently added MinimumVersion property to the software/<functional-id>/ path since it's tied to the BMC version.
Tested:
root@witherspoon:~# busctl
get-property xyz.openbmc_project.Software.BMC.Updater
/xyz/openbmc_project/software/26cddfb1
xyz.openbmc_project.Software.MinimumVersion MinimumVersion
s "2.15.0"
Change-Id: I6c84d90282f4d58d0f776e9482d867208bbfe077
> 1050: Move the MinimumVersion property to the id path

- item_updater.cpp
- item_updater.hpp
Per feedback from the bmcweb maintainers, move the recently added MinimumVersion property to the software/<functional-id>/ path since it's tied to the BMC version.
Tested:
root@witherspoon:~# busctl
get-property xyz.openbmc_project.Software.BMC.Updater
/xyz/openbmc_project/software/26cddfb1
xyz.openbmc_project.Software.MinimumVersion MinimumVersion
s "2.15.0"
Change-Id: I6c84d90282f4d58d0f776e9482d867208bbfe077
> 1060: Move the MinimumVersion property to the id path

- item_updater.cpp
- item_updater.hpp
Per feedback from the bmcweb maintainers, move the recently added MinimumVersion property to the software/<functional-id>/ path since it's tied to the BMC version.
Tested:
root@witherspoon:~# busctl
get-property xyz.openbmc_project.Software.BMC.Updater
/xyz/openbmc_project/software/26cddfb1
xyz.openbmc_project.Software.MinimumVersion MinimumVersion
s "2.15.0"
Change-Id: I6c84d90282f4d58d0f776e9482d867208bbfe077
> 1110: Move the MinimumVersion property to the id path

- item_updater.hpp
The LID interface was mistakenly removed when the minimum ship level functionality was rebased with upstream.
Change-Id: I4a7fb515e93a1672740e677d7d88b486acdab7d9
> item_updater: Restore the LID interface

- item_updater.hpp
```
The LID interface was mistakenly removed when the minimum ship level
functionality was rebased with upstream.
Change-Id: I4a7fb515e93a1672740e677d7d88b486acdab7d9
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>```
> 1060: item_updater: Restore the LID interface (#39)

- item_updater.hpp
```
The LID interface was mistakenly removed when the minimum ship level
functionality was rebased with upstream.
Change-Id: I4a7fb515e93a1672740e677d7d88b486acdab7d9
Signed-off-by: Adriana Kobylak <anoo@us.ibm.com>```
> 1110: item_updater: Restore the LID interface (#39)

- item_updater.cpp
- msl_verify.cpp
- msl_verify.hpp
Upon start, the software updater service reads the Minimum Ship Level from the com.ibm.ipzvpd.VSYS FV property on the bmc card and from flash memory in /var/lib/phosphor-bmc-code-mgmt/msl-data. Then it syncs them up with one another, prioritizing first the bmc card, then flash memory.
The sync mechanism is needed to keep a backup of the value in order to restore it if the planar or BMC card are replaced.
Tested: Verified the syncing is done upon reboot. Verified no syncing is done when the value is all spaces (default), and when the VPD service is not running.
Change-Id: I996f373711ac958a98e01fd65b09203016cbd69b
> 1050: msl: Add sync method

- item_updater.cpp
- msl_verify.cpp
- msl_verify.hpp
Upon start, the software updater service reads the Minimum Ship Level from the com.ibm.ipzvpd.VSYS FV property on the bmc card and from flash memory in /var/lib/phosphor-bmc-code-mgmt/msl-data. Then it syncs them up with one another, prioritizing first the bmc card, then flash memory.
The sync mechanism is needed to keep a backup of the value in order to restore it if the planar or BMC card are replaced.
Tested: Verified the syncing is done upon reboot. Verified no syncing is done when the value is all spaces (default), and when the VPD service is not running.
Change-Id: I996f373711ac958a98e01fd65b09203016cbd69b
> 1060: msl: Add sync method

- item_updater.cpp
- msl_verify.cpp
- msl_verify.hpp
Upon start, the software updater service reads the Minimum Ship Level from the com.ibm.ipzvpd.VSYS FV property on the bmc card and from flash memory in /var/lib/phosphor-bmc-code-mgmt/msl-data. Then it syncs them up with one another, prioritizing first the bmc card, then flash memory.
The sync mechanism is needed to keep a backup of the value in order to restore it if the planar or BMC card are replaced.
Tested: Verified the syncing is done upon reboot. Verified no syncing is done when the value is all spaces (default), and when the VPD service is not running.
Change-Id: I996f373711ac958a98e01fd65b09203016cbd69b
> 1110: msl: Add sync method

- activation.cpp
Verify the signature first, because the image could had been manually modified to pass the UAK check by changing the build date on the MANIFEST file. The update would still fail the signature check as it is, but makes more sense to validate the siganture first.
Change-Id: I3814f5560fbbbaf16e6415080ee7cce4d5da0d7e
> 1110: activation: Verify signature before UAK

- lid.cpp
- lid.hpp
- uak_verify.cpp
Parse all the marker lid fields first before doing the verifications because the uak check relies on the SPNM field, which currently is placed after the FIPP field, causing the UAK check to have an empty version string.
If the version string was empty, the UAK check was not logging an error. Need to log an error to tell PHYP that the update has failed. Although an empty version string should not be seen again unless there's an error in the marker lid.
For the msl, read version string before appending null terminator. Need to add the null terminator after reading the string, otherwise the read operation will overwrite the null terminator.
Change-Id: Icb84873836e1a44cafc489b45b39d90701e84e32
> 1060: lid: validate: Fix parsing logic

- lid.cpp
- lid.hpp
- uak_verify.cpp
Parse all the marker lid fields first before doing the verifications because the uak check relies on the SPNM field, which currently is placed after the FIPP field, causing the UAK check to have an empty version string.
If the version string was empty, the UAK check was not logging an error. Need to log an error to tell PHYP that the update has failed. Although an empty version string should not be seen again unless there's an error in the marker lid.
For the msl, read version string before appending null terminator. Need to add the null terminator after reading the string, otherwise the read operation will overwrite the null terminator.
Change-Id: Icb84873836e1a44cafc489b45b39d90701e84e32
> 1110: lid: validate: Fix parsing logic

- msl_verify.hpp
Increase the size of the major release variable so that it can hold values that are bigger than 255, such as 1060, so that comparisons against different Power generations can be done, such as against 1110.
Change-Id: Icd61bbe457de6f3c8a71a4bb555f6efbab3508b0
> msl: Increase the size of the major release

- obmc-flash-bmc
IMA requires the initramfs type to be tmpfs. Since the u-boot environment is not updated during a code update, update this variable as part of the code update flow.
Change-Id: I398b1a742a4bf1d6a6a26459134145e3f89be041
> obmc-flash-bmc: mmc: Add rootfstype=tmpfs
